# fly.toml app configuration file generated for ebay-watch on 2026-03-29T00:52:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ebay-watch'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  EBAY_PW_HEADLESS = '1'
  EBAY_WATCH_DATA_DIR = '/data'
  PORT = '8080'
  PLAYWRIGHT_TIMEOUT_SECS = '300'
  EBAY_SKIP_ITEM_GALLERY = '1'

[[mounts]]
  source = 'ebay_watch_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 1
